# This is a basic workflow to help you get started with Actions

name: Hardhat Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1

      # Runs a single command using the runners shell
      - name: Run npm install
        run: yarn

      # Runs a set of commands using the runners shell
      - name: Run build
        run: yarn build

      - name: Run size-contract
        run: npx hardhat size-contracts

      # Runs a set of commands using the runners shell
      - name: Run test
        env:
          ALCHEMY_KEY: ${{ secrets.ALCHEMY_KEY }}
          REPORT_GAS: true
          REPORT_GAS_COINMARKETCAP_API_KEY: ${{ secrets.REPORT_GAS_COINMARKETCAP_API_KEY }}
        run: yarn test
